services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: todo-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo_db
      - PORT=5000
    depends_on:
      - mongo
    volumes:
      - ./server:/app

  client:
    build: ./client
    container_name: todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app

volumes:
  mongo-data:
