FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o fizzbuzz .

FROM scratch

COPY --from=builder /app/fizzbuzz /fizzbuzz

EXPOSE 8080

CMD ["/fizzbuzz", "serve", "--port", "8080"]
